### PR TITLE
Core: #30 preserve query parameter encoding

### LINKED ISSUE #30: Query parameter containing encoded &
The query parameter `foo & bar` is encoded as `foo%20%26%20bar`

Request:
```
GET /test?custom=foo%20%26%20bar
```

Try following java code:

```java
String requestText = "GET /test?custom=foo%20%26%20bar HTTP/1.1\n" +
    "Host: localhost:8090\n" +
    "\n";
RawHttp http = new RawHttp();
RawHttpRequest httpRequest = http.parseRequest(requestText);
try (Socket socket = new Socket("localhost", 8090)) {
    httpRequest.writeTo(socket.getOutputStream());
    RawHttpResponse<?> httpResponse = http.parseResponse(socket.getInputStream());
    String responseText = httpResponse.eagerly()
        .toString();
    socket.close();

    System.out.println(responseText);
}
```

**Expected:**

Server-side, 1 query parameter:

* name `custom`
* value (decoded) `foo & bar`

**Current:**

2 parameters:

* first:
  * name `custom`
  * value `foo `
* second:
  * name ` bar`
  * no value

---

I think that this URI rewrite (line 88) might be the root cause:

https://github.com/renatoathaydes/rawhttp/blob/a456bf9c5a6d0b33b31111f12d99b4b2857fd4a4/rawhttp-core/src/main/java/rawhttp/core/RequestLine.java#L81-L93

Stacktrace
```
Thread [main] (Suspended (breakpoint at line 93 in RequestLine))	
	RequestLine.toString() line: 93	
	RequestLine.writeTo(OutputStream) line: 70	
	RawHttpRequest(HttpMessage).writeTo(OutputStream, int) line: 152	
	RawHttpRequest(HttpMessage).writeTo(OutputStream) line: 141	
	RawHttpMain.main(String[]) line: 28	
```

The `pathURI` on line 93 is wrong: 

Is: `"/test?custom=foo%20&%20bar"`
Expected: `"/test?custom=foo%20%26%20bar"`

---

Feedback is welcomed.

I am happy to contribute a PR for this issue, but I would like to know the direction I should take.

### PR DESCRIPTION
**Pull request by jmini**
Fixes #30.

### CODE REVIEW

File: rawhttp-core/src/main/java/rawhttp/core/RequestLine.java [hunk 1]
```diff
@@ -85,12 +85,18 @@ public String toString() {
         }
         try {
             // only path and query are sent to the server
-            pathURI = new URI(null, null, null, -1, path, uri.getQuery(), null);
```
Comment (renatoathaydes) [inline rawhttp-core/src/main/java/rawhttp/core/RequestLine.java:88]: Wouldn't it have worked if you only had changed `uri.getQuery()` to `uri.getRawQuery()`?

**Comment by renatoathaydes** [comment]
Thanks for the PR!
Not sure why this PR does not seem to have triggered the tests.
Have you run the full test suite after your changes?

If all tests are passing, I think this is a good change! I will do some manual testing here and make sure we're not missing something before merging.

File: rawhttp-core/src/test/kotlin/rawhttp/core/RequestLineTest.kt [hunk 2]
```diff
@@ -142,19 +142,22 @@ class RequestLineTest {
...
+        val table = table(headers("Request line", "raw query", "decoded query", "Expected String"),
+                row("GET /hi?a=1", "a=1", "a=1", "GET /hi?a=1 HTTP/1.1"),
+                row("GET /hi?a=1&b=2", "a=1&b=2", "a=1&b=2", "GET /hi?a=1&b=2 HTTP/1.1"),
+                row("GET /hi?a=hi%20w", "a=hi%20w", "a=hi w", "GET /hi?a=hi%20w HTTP/1.1"),
+                row("GET /hi?a=foo%20%26%20bar", "a=foo%20%26%20bar", "a=foo & bar", "GET /hi?a=foo%20%26%20bar HTTP/1.1"),
                 row("GET /hi?%2F%2Fencoded%3Fa%3Db%26c%3Dd&json=%7B%22a%22%3A%20null%7D",
                         "%2F%2Fencoded%3Fa%3Db%26c%3Dd&json=%7B%22a%22%3A%20null%7D",
-                        "//encoded?a=b&c=d&json={\"a\": null}")
+                        "//encoded?a=b&c=d&json={\"a\": null}",
+                        "GET /hi?%2F%2Fencoded%3Fa%3Db%26c%3Dd&json=%7B%22a%22%3A%20null%7D HTTP/1.1")
```
Comment (renatoathaydes) [inline rawhttp-core/src/test/kotlin/rawhttp/core/RequestLineTest.kt:153]: I can't believe my test cases failed to pick up this issue!

File: rawhttp-core/src/main/java/rawhttp/core/RequestLine.java (hunk 1 above)
Comment (renatoathaydes) [reply rawhttp-core/src/main/java/rawhttp/core/RequestLine.java:88]: I had a look and it seems that it would've been impossible to use the query like this, because if the original query in `uri` contained a escaped character, it would be un-escaped here by calling `getQuery()`, but then the original query could never be recovered... this is a problem with URL encoding: it's one-way only. Once you decode it, you can't know the original unless you keep each part separated and encode them individually. This is why `pathURI` could never include the original query below.
Thanks for picking this up @jmini  I will merge and clean up this a little bit as the use of a new `URI` in this code becomes redundant now.

File: rawhttp-core/src/test/kotlin/rawhttp/core/RequestLineTest.kt (hunk 2 above)
Comment (renatoathaydes) [reply rawhttp-core/src/test/kotlin/rawhttp/core/RequestLineTest.kt:153]: Looks like the test didn't just miss this case, it also missed testing the `toString()` method (even though I do test that in other places - which very unluckily, also failed to check this particular case).

**Comment by renatoathaydes** [comment]
All tests were passing, so I merged it. Thanks again.

File: rawhttp-core/src/main/java/rawhttp/core/RequestLine.java (hunk 1 above)
Comment (jmini) [reply rawhttp-core/src/main/java/rawhttp/core/RequestLine.java:88]: I also thought `uri.getRawQuery()` was the solution… But as you wrote it is not the case.
